
#
# Sprinkle - Asset management library
# 
# @author        Edmundas Kondrašovas <as@edmundask.lt>
# @license       http://www.opensource.org/licenses/MIT
#

jquery:
  type: js
  minify: true
  combine: false
  versions:
    default: http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js
    1.5.1: http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js
    1.6.4: http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.js

# -------------------------------------------------------------------------
# Asset groups
# -------------------------------------------------------------------------

js-libs:
  type: group
  assets: [jquery]